groceries_list/app/urls.py
from django.urls import path,include
from . import views
# from rest_framework import routers

# router=routers.DefaultRouter()
# # # router.register("signupapi",views.Customerapiview, basename='signupapi'),
# # router.register("adminproductapi/",views.adminproductapi.as_view, basename='ff'),
# router.register("productapi", views.Productapi, basename="Productapi"),






app_name = "app"

urlpatterns = [

    # User pages
    path('allproductapiall/',views.allproductapiall,name='allproductapiall'),
   
    # path("adminproduct/",views.adminproductapi.as_view(), name='adminproduct'),
    # path("ap/",include(router.urls)),
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.contact, name="contact"),
    path("all-products/", views.AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", views.ProductDetailView.as_view(), name="productdetail"),
    path("add-to-cart-<int:pro_id>/", views.AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", views.MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", views.ManageCartView.as_view(), name="managecart"),
    path("manage-cart/<int:cp_id>/", views.manage_cart, name="managecart"),

    path("empty-cart/", views.EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("register/",views.CustomerRegistrationView.as_view(), name="customerregistration"),
    # path('registerview/',views.registerview,name='registerview'),
    path("logout/", views.CustomerLogoutView.as_view(), name="customerlogout"),

    path("login/", views.CustomerLoginView.as_view(), name="customerlogin"),
    path("profile/", views.CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", views.CustomerOrderDetailView.as_view(),name="customerorderdetail"),
    #path("search/", views.SearchView.as_view(), name="search"),
    path('pay/',views.razorpay,name='pay'),
    
    path('pay/success',views.success,name='success'),
    # Admin pages
    path("admin-login/", views.AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", views.AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", views.AdminOrderDetailView.as_view(),name="adminorderdetail"),
    path("admin-all-orders/", views.AdminOrderListView, name="adminorderlist"),
    # path("admin-all-orders/", views.AdminOrderListView.as_view(), name="adminorderlist"),AdminOrderListView,
    path("admin-order-<int:pk>-change/",views.AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),
    path("admin-product/list/", views.AdminProductListView.as_view(),name="adminproductlist"),
    path("admin-users/list/", views.AdminUserListView.as_view(),name="adminuserlist"),
    # path("admin-product/add/", views.AdminProductCreateView.as_view(),name="adminproductcreate"),
    path("admin-product/add/", views.image,name="adminproductcreate"),
    path('edit/<int:id>/', views.update_data,name='edit'),
    path('delete/<int:id>/', views.DeleteView.as_view(),name='delete'),
    path('userdelete/<int:id>/', views.DeleteUserView.as_view(),name='userdelete'),
    # path('userdelete/<int:id>/', views.DeleteUserView,name='userdelete'),
    path('userListView',views.userListView,name='userListView'),
    path('customerdelete/<int:id>/', views.DeletecustomerView.as_view(),name='customerdelete'),
    # path('customerdelete/<int:id>/', views.DeletecustomerView,name='customerdelete'),
    path('adminfeedback/',views.adminfeedback,name='adminfeedback'),
    path("admin-order/<int:pk>/", views.AdminOrderDetailView.as_view(),name="adminorderdetail"),
    # path("adminfeedbackorder/<int:pk>/", views.AdminOrderfeedbackDetailView.as_view(),name="adminorderfeedbackdetail"),
    path("adminfeedbackorder/", views.AdminOrderfeedbackDetailView,name="adminorderfeedbackdetail"),
    path("admincategorylist", views.AllcategoryView.as_view(),name="admincategorylist"),
    path('admincategorycreate/',views.admincategorycreate.as_view(),name='admincategorycreate'), 
    path("adminlogout/", views.adminLogoutView.as_view(), name="adminlogout"),


    #userapi urls
    path("api/", views.home.as_view(), name="home"),
    path("api/categoryapi/", views.categoryapi, name="categoryapi"),
    path("api/product/<int:id>/", views.product_detail, name="productdetail"),
    path("api/addtocart/<int:pro_id>/", views.add_cart, name="addtocart"),
    path('api/managecart/<int:id>/',views.managecart,name="managecart"),
    path("api/contact/", views.contact, name="contact"),
    path("api/profile/", views.profile, name="profile"),
    path("api/order/", views.order,name="customerorderdetail"),
    path("api/manage_cart/",views.manage_cart,name="manage_cartapi" ),
    #path('api/increment/<int:product_id>/',views.IncrementCartProductView.as_view(),name='incrementcartproduct'),

    
    # 
    path("api/customerinfo/<int:pro_id>/", views.customerinfo,name="customerinfo"),
    path("api/displayorder/", views.displayorder,name="displayorder"),
    path('loginapi/', views.loginView.as_view(), name='loginapi'),
    # 
    path('ProductDetailupdatedelete/<int:pk>/', views.ProductDetailupdatedelete.as_view(), name='ProductDetailupdatedelete'),
    path('ProductListcreatepost/', views.ProductListcreatepost.as_view(), name='ProductListcreatepost'),
    # 
    path("signupapi/",views.Customerapiview.as_view(), name='signupapi'),
    path("api/stockapi/", views.stockapi, name="stockapi"),
    path("api/adminuserdisplay/", views.adminuserdisplay, name="adminuserdisplay"),
   
    path("api/adminproductapicr/", views.adminproductapicr, name="adminproductapicr"),
    path("api/adminproductud/<int:pro_id>/", views.adminproductud, name="adminproductud"),
    path("api/adminfeedbackdisplay/", views.adminfeedbackdisplay, name="adminfeedbackdisplay"),
    path("api/LogoutView/", views.LogoutView.as_view(), name="LogoutView"),
    
    #Image Upload
    path('upload/', views.upload_image, name='upload_image'),


]

groceries_list/groceries_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceries_list/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator
from cryptography.fernet import Fernet
import base64
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
   
    def __str__(self):
        return self.title

class Stock(models.Model):
    title = models.CharField(max_length=200)
   
    def __str__(self):
        return self.title
    




types_of_weight = (
    ("kg", "kg"),
    ("pieces", "pieces"),
    ("liters", "liters"),
    ("grams", "grams"),
    
)
def upload_path(instance,filename):
    return '/'.join(['products',str(instance)])

# class Product(models.Model):
#     title = models.CharField(max_length=200)
#     stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to="products")
#     image_data = models.BinaryField(null=False)
#     marked_price = models.PositiveIntegerField()
#     selling_price = models.PositiveIntegerField()
#     quantity = models.PositiveIntegerField()
#     date = models.DateTimeField(auto_now_add=True)
#     type_of_quantity = models.CharField(max_length=50, choices=types_of_weight)
#     description = models.TextField()
    
#     def __str__(self):
#         return self.title
#     def save(self, *args, **kwargs):
#         # Encrypt the binary data of the image file
#         if self.image:
#             key = Fernet.generate_key()
#             fernet = Fernet(key)
#             encrypted_data = fernet.encrypt(self.image.read())
#             self.image_data = encrypted_data
        
#         super().save(*args, **kwargs)
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from urllib.parse import urljoin

class Product(models.Model):
    title = models.CharField(max_length=200)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    type_of_quantity = models.CharField(max_length=50, choices=types_of_weight)
    description = models.TextField()
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Save the image file to the file system
        super().save(*args, **kwargs)
        
        # Set the image_data field to the URL of the image file
        if self.image:
            self.image_data = urljoin(settings.MEDIA_URL, self.image.name)

        super().save(*args, **kwargs)


                  



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title

class Cart(models.Model):
    customer = models.ForeignKey(
    Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


# class CartProduct(models.Model):
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     rate = models.PositiveIntegerField()
#     quantity = models.PositiveIntegerField()
#     subtotal = models.PositiveIntegerField()

#     def __str__(self):
#         return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


class CartProduct(models.Model):
    title=models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    quantity = models.IntegerField()
    # subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    
    ("Razor Pay","Razor Pay"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_to = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Razor Pay")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

class ContactModel(models.Model):
    orderid=models.ForeignKey(Order, on_delete=models.CASCADE,null=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    feedback = models.CharField(max_length=100,null=True)
    rating=models.PositiveIntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)],null=True)

    
  
class Image(models.Model):
    image=models.TextField()

groceries_list/templates/about.html
{% extends 'base.html' %}

{% block title %}About us{% endblock %}

{% block content %}
    <h1>We are the emerging Groceres List.</h1>
{% endblock %}

groceries_list/templates/admincategorylist.html
{% extends 'base.html' %}
{% block title %}All Products{% endblock %}


{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col-md-12">
            <h3>All category list</h3><hr>
            <a href="{% url 'app:admincategorycreate' %}" class="btn btn-success">Add New category</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>title</th>
                        </tr>
                </thead>
                <tbody>
                  {% for i in allcategorylist %}
                    <tr>
                        <td>{{i.id}}</td>
                        <td>{{i.sku}}</td>
                        
                       
                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>
    </div>
</div>
{% endblock %}

groceries_list/templates/adminhome.html
{% extends 'base.html' %}
{% block title %}Admin Home{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                       
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'app:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

groceries_list/templates/adminorderfeedbackdetail.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Order Detail{% endblock  %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <hr>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
             <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank"
                                href="{% url 'app:productdetail' cp.product.sku %}">{{cp.product.title}}({{cp.product.id}})</a>
                        </td>
                        
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
          
        </div>
    </div>
</div>
{% endblock %}

groceries_list/templates/adminorderlist.html
{% extends 'base.html' %}

{% block title %}All Orders {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>All Orders</h3><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'app:adminorderdetail' order.id %}">#ORDER_{{order.id}}</a></td>
                        
                        <td>{{order.created_at}}</td>
                        <td>{{order.total}}</td>
                        <td>{{order.order_status}}</td>
            
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

groceries_list/templates/adminproductlist.html
{% extends 'base.html' %}
{% block title %}All Products{% endblock %}


{% block content %}
<div class="container"> 
    <div class="row">
        <div class="col-md-12">
            <h3>All Product list</h3><hr>
            <a href="{% url 'app:adminproductcreate' %}" class="btn btn-success">Add New Product</a>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product Title</th>
                        <th>Image</th>
                        <th>Price</th>
                        <th>Available quantity</th>
                        <th>date</th>
                        <th>Changes</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for p in allproducts %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{p.title}}</td>
                        
                        <td><img src="{{p.image.url}}" style="height: 60px;" alt=""></td>
                        <td>{{p.selling_price}}</td>
                        <td>{{p.quantity}} </td>
                        <td>{{p.date}} </td>
                        <td><a href="/edit/{{p.id}}" class="btn btn-warning btn-sm">Edit</a></td>
                        <td><a href="/delete/{{p.id}}" class="btn btn-danger btn-sm" >Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
                
            </table>
        </div>
    </div>
</div>
{% endblock %}

groceries_list/templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <h3>All Products</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3">
            <div class="m-4">
                <h4><a href="{% url 'app:productdetail' p.title %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                <p class="mt-3">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
               
                {% if p.quantity <= 1 %}
<h5 style="color:red;">Out of Stock</h5>
{% else %}
    <a href="{% url 'app:addtocart' p.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
    <a href="http://192.168.3.158:8008/pay/" class="btn btn-outline-secondary">buy</a>
{% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

groceries_list/templates/customerlogin.html
{% extends 'base.html' %}

{% block title %}Customer Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
    
    body {
        background-image: url('https://t3.ftcdn.net/jpg/01/79/46/70/240_F_179467072_NlfgeVIoDyCtHOLjVgorvna7orVw08ID.jpg');
        height: 800px;
        background-repeat: no-repeat;
        background-size: cover;

    
    }
    
</style>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Login</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                
                <button class="btn btn-primary">Login </button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p> or dont have account? <a href="{% url 'app:customerregistration' %}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p>
        </div>
    </div>
</div>

</body>
{% endblock %}

groceries_list/templates/mycart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<style type="text/css">
    body {
        background-image: url('https://t3.ftcdn.net/jpg/01/79/46/70/240_F_179467072_NlfgeVIoDyCtHOLjVgorvna7orVw08ID.jpg');
        height: 800px;
        background-repeat: no-repeat;
        background-size: cover;

    
    }
</style>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}KG</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'app:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'app:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'app:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'app:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'app:checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
{% endblock %}

groceries_list/templates/pay.html
Click the below button to pay the amount
<form action="success" method='GET'>
<script
    src="https://checkout.razorpay.com/v1/checkout.js"    
    data-key="rzp_test_tx5GNwIVukb1M5"
    data-amount="50000"
    data-currency="INR"
    data-order_id="{{product.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="Professional Cipher"
    data-description="parcel delivery payment"
    data-image="https://example.com/your_logo.jpg"    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"></script>
</form>

groceries_list/templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Product: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} </h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</h5>
            
            {% if product.quantity <= 1 %}
            <h5 style="color:red;">Out of Stock</h5>
            {% else %}
                <a href="{% url 'app:addtocart' product.id %}" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
            {% endif %}

          
           


<!-- Button trigger modal -->


<!-- Central Modal Small -->
<div class="modal fade" id="centralModalSm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
aria-hidden="true">

<!-- Change class .modal-sm to change the size of the modal -->
<div class="modal-dialog modal-sm" role="document">


<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title w-100" id="myModalLabel">Modal title</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p>product added successfully </p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-primary btn-sm" data-dismiss="modal">Close</button>
    
  </div>
</div>
</div>
</div> 
          
            <hr>
            <hr>
            <h1>Details</h1>
            <p>{{product.description}}</p>

            <hr>
            
            <table class="table table-striped">
                <thead>
                    <tr>
                        
                        <th>Feedback</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in us %}
                    <tr>
                       
                    <td>{{i.Feedback}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>

    

</div>
{% endblock %}

groceries_list/templates/success.html
<style type="text/css">
    body {
        background-image: url('https://t3.ftcdn.net/jpg/01/79/46/70/240_F_179467072_NlfgeVIoDyCtHOLjVgorvna7orVw08ID.jpg');
        height: 800px;
        background-repeat: no-repeat;
        background-size: cover;

    
    }
</style>
<body><h1 style="text-align: center;padding-top:180px;"> Payment Success</h1></body>

groceries_list/templates/upload_form.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image">
    <input type="submit" value="Upload">
  </form>
  

groceries_list/templates/upload_success.html
<h1>Image uploaded successfully!</h1>
<img src="data:image/jpeg;base64,{{ image_model.image}}"/>